# Generated by Django 5.1.5 on 2025-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_ftp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='status',
        ),
        migrations.AddField(
            model_name='url',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
